name: Prerelease PR

on:
  pull_request_target:
    types: [labeled]

jobs:
  prerelease:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'prerelease') && github.event.pull_request.state == 'open' && github.event.pull_request.draft == false && github.event.pull_request.mergeable_state == 'clean' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '22.x'
          cache: pnpm

      - name: Install script dependencies
        run: |
          pnpm install -C scripts/prerelease

      - name: Publish
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_REPO_URL: ${{ github.event.pull_request.head.repo.clone_url }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          ./scripts/prerelease/node_modules/.bin/tsx ./scripts/prerelease/ci-prerelease.ts
